name: PortalOverrides
version: '${project.version}'
main: net.jadedmc.portaloverrides.PortalOverrides
api-version: 1.13
softdepend: [WorldGuard]
authors: [JadedMC]
description: Overrides Portal Behavior Based On Various Settings
website: https://www.jadedmc.net
