name: PortalOverrides
version: '${project.version}'
main: net.jadedmc.portaloverrides.PortalOverrides
api-version: 1.19
softdepend: [WorldGuard]
authors: [JadedMC]
description: Override's Portal Behavior Based On Various Settings
website: https://www.jadedmc.net
